/* eslint import/prefer-default-export: 0 */
export const northKoreaProvinces = [
  'Hyesan',
  'Kusong',
  'Rason',
  "Kimch'aek",
  'Anju',
  "Tokch'on",
  'Kanggye',
  'Haeju',
  "P'yongsong",
  "Sunch'on",
  'Sariwon',
  'Kaesong',
  "Kaech'on",
  "Tanch'on",
  'Sinuiju',
  'Wonsan',
  "Namp'o",
  "Ch'ongjin",
  'Hamhŭng',
  'Pjongjang',
];
